### ISSUE TITLE
Trigger -> Status -> Cast does not work

### ISSUE THREAD

**Issue by taanzfour** [SolidBrave/weakaura-2.16.3-legion-port#1]
Status -> Cast trigger does not function, when a cast starts it immediately disappears.
Not sure if you're still willing to work on this WeakAaura but a fix for this would be much appreciated as this is about the only big issue with it.
![image_2023-10-22_152756151](https://github.com/SolidBrave/weakaura-2.16.3-legion-port/assets/108298308/16d71013-3d91-4b68-b6c5-3b69e7838e95)

**Comment by taanzfour** [comment]
This is what happens in-game, the trigger shows up for about the first 0.1 second then disappears.
![statuscasttrigger](https://github.com/SolidBrave/weakaura-2.16.3-legion-port/assets/108298308/84f10d2c-88b4-468e-a110-f7fecddd178c)

**Comment by Netherborne** [comment]
made a pull request for the fix

**Comment by SolidBrave** [comment]
@Taan04  @kyriaziskokkinos  Hay never noticed that. I'll merge it :D
